-- Migration number: 0003 	 skills taxonomy
--
-- The taxonomy lives in the database rather than the bundle so it can grow
-- without a deploy: a skill nobody thought of on launch day is an INSERT, not
-- a release. Everything else in src/lexicons/ is bundled because it is small
-- and has to be node-testable without a database.
--
-- `alias` is the lookup key and is already normalised (lowercase, trimmed).
-- `canonical` is what the reader is shown. `kind` separates the hard skills a
-- keyword search can match from the soft skills that give a parser nothing.

CREATE TABLE skills (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  canonical TEXT NOT NULL,
  alias TEXT NOT NULL UNIQUE,
  family TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('hard', 'soft'))
);
CREATE INDEX idx_skills_canonical ON skills(canonical);

INSERT INTO skills (canonical, alias, family, kind) VALUES
  ('Python', 'python', 'languages', 'hard'),
  ('JavaScript', 'javascript', 'languages', 'hard'),
  ('JavaScript', 'js', 'languages', 'hard'),
  ('JavaScript', 'ecmascript', 'languages', 'hard'),
  ('TypeScript', 'typescript', 'languages', 'hard'),
  ('TypeScript', 'ts', 'languages', 'hard'),
  ('Java', 'java', 'languages', 'hard'),
  ('C#', 'c#', 'languages', 'hard'),
  ('C#', 'c sharp', 'languages', 'hard'),
  ('C#', 'csharp', 'languages', 'hard'),
  ('C++', 'c++', 'languages', 'hard'),
  ('C', 'c', 'languages', 'hard'),
  ('Go', 'go', 'languages', 'hard'),
  ('Rust', 'rust', 'languages', 'hard'),
  ('Ruby', 'ruby', 'languages', 'hard'),
  ('PHP', 'php', 'languages', 'hard'),
  ('Swift', 'swift', 'languages', 'hard'),
  ('Kotlin', 'kotlin', 'languages', 'hard'),
  ('Scala', 'scala', 'languages', 'hard'),
  ('R', 'r', 'languages', 'hard'),
  ('MATLAB', 'matlab', 'languages', 'hard'),
  ('Perl', 'perl', 'languages', 'hard'),
  ('Objective-C', 'objective-c', 'languages', 'hard'),
  ('Dart', 'dart', 'languages', 'hard'),
  ('Elixir', 'elixir', 'languages', 'hard'),
  ('Haskell', 'haskell', 'languages', 'hard'),
  ('Julia', 'julia', 'languages', 'hard'),
  ('Groovy', 'groovy', 'languages', 'hard'),
  ('Lua', 'lua', 'languages', 'hard'),
  ('Shell', 'shell', 'languages', 'hard'),
  ('Bash', 'bash', 'languages', 'hard'),
  ('PowerShell', 'powershell', 'languages', 'hard'),
  ('VBA', 'vba', 'languages', 'hard'),
  ('COBOL', 'cobol', 'languages', 'hard'),
  ('Fortran', 'fortran', 'languages', 'hard'),
  ('Assembly', 'assembly', 'languages', 'hard'),
  ('SQL', 'sql', 'languages', 'hard'),
  ('PL/SQL', 'pl/sql', 'languages', 'hard'),
  ('T-SQL', 't-sql', 'languages', 'hard'),
  ('HTML', 'html', 'languages', 'hard'),
  ('CSS', 'css', 'languages', 'hard'),
  ('Sass', 'sass', 'languages', 'hard'),
  ('XML', 'xml', 'languages', 'hard'),
  ('YAML', 'yaml', 'languages', 'hard'),
  ('JSON', 'json', 'languages', 'hard'),
  ('GraphQL', 'graphql', 'languages', 'hard'),
  ('Solidity', 'solidity', 'languages', 'hard'),
  ('React', 'react', 'web', 'hard'),
  ('Angular', 'angular', 'web', 'hard'),
  ('Vue.js', 'vue.js', 'web', 'hard'),
  ('Vue.js', 'vue', 'web', 'hard'),
  ('Vue.js', 'vuejs', 'web', 'hard'),
  ('Svelte', 'svelte', 'web', 'hard'),
  ('Next.js', 'next.js', 'web', 'hard'),
  ('Next.js', 'nextjs', 'web', 'hard'),
  ('Nuxt', 'nuxt', 'web', 'hard'),
  ('Node.js', 'node.js', 'web', 'hard'),
  ('Node.js', 'node', 'web', 'hard'),
  ('Node.js', 'nodejs', 'web', 'hard'),
  ('Express', 'express', 'web', 'hard'),
  ('Django', 'django', 'web', 'hard'),
  ('Flask', 'flask', 'web', 'hard'),
  ('FastAPI', 'fastapi', 'web', 'hard'),
  ('Rails', 'rails', 'web', 'hard'),
  ('Laravel', 'laravel', 'web', 'hard'),
  ('Spring', 'spring', 'web', 'hard'),
  ('Spring Boot', 'spring boot', 'web', 'hard'),
  ('ASP.NET', 'asp.net', 'web', 'hard'),
  ('jQuery', 'jquery', 'web', 'hard'),
  ('Bootstrap', 'bootstrap', 'web', 'hard'),
  ('Tailwind CSS', 'tailwind css', 'web', 'hard'),
  ('Redux', 'redux', 'web', 'hard'),
  ('webpack', 'webpack', 'web', 'hard'),
  ('Vite', 'vite', 'web', 'hard'),
  ('Babel', 'babel', 'web', 'hard'),
  ('REST', 'rest', 'web', 'hard'),
  ('SOAP', 'soap', 'web', 'hard'),
  ('WebSockets', 'websockets', 'web', 'hard'),
  ('Progressive Web Apps', 'progressive web apps', 'web', 'hard'),
  ('Web Components', 'web components', 'web', 'hard'),
  ('PostgreSQL', 'postgresql', 'data', 'hard'),
  ('PostgreSQL', 'postgres', 'data', 'hard'),
  ('PostgreSQL', 'psql', 'data', 'hard'),
  ('MySQL', 'mysql', 'data', 'hard'),
  ('SQL Server', 'sql server', 'data', 'hard'),
  ('SQL Server', 'mssql', 'data', 'hard'),
  ('SQL Server', 'ms sql', 'data', 'hard'),
  ('Oracle Database', 'oracle database', 'data', 'hard'),
  ('MongoDB', 'mongodb', 'data', 'hard'),
  ('Redis', 'redis', 'data', 'hard'),
  ('Cassandra', 'cassandra', 'data', 'hard'),
  ('DynamoDB', 'dynamodb', 'data', 'hard'),
  ('Elasticsearch', 'elasticsearch', 'data', 'hard'),
  ('Snowflake', 'snowflake', 'data', 'hard'),
  ('BigQuery', 'bigquery', 'data', 'hard'),
  ('Redshift', 'redshift', 'data', 'hard'),
  ('Databricks', 'databricks', 'data', 'hard'),
  ('Spark', 'spark', 'data', 'hard'),
  ('Spark', 'apache spark', 'data', 'hard'),
  ('Spark', 'pyspark', 'data', 'hard'),
  ('Hadoop', 'hadoop', 'data', 'hard'),
  ('Hive', 'hive', 'data', 'hard'),
  ('Kafka', 'kafka', 'data', 'hard'),
  ('Kafka', 'apache kafka', 'data', 'hard'),
  ('Airflow', 'airflow', 'data', 'hard'),
  ('Airflow', 'apache airflow', 'data', 'hard'),
  ('dbt', 'dbt', 'data', 'hard'),
  ('ETL', 'etl', 'data', 'hard'),
  ('Data warehousing', 'data warehousing', 'data', 'hard'),
  ('Data modelling', 'data modelling', 'data', 'hard'),
  ('SQLite', 'sqlite', 'data', 'hard'),
  ('MariaDB', 'mariadb', 'data', 'hard'),
  ('Neo4j', 'neo4j', 'data', 'hard'),
  ('ClickHouse', 'clickhouse', 'data', 'hard'),
  ('Firestore', 'firestore', 'data', 'hard'),
  ('AWS', 'aws', 'cloud', 'hard'),
  ('AWS', 'amazon web services', 'cloud', 'hard'),
  ('Azure', 'azure', 'cloud', 'hard'),
  ('Azure', 'microsoft azure', 'cloud', 'hard'),
  ('GCP', 'gcp', 'cloud', 'hard'),
  ('GCP', 'google cloud', 'cloud', 'hard'),
  ('GCP', 'google cloud platform', 'cloud', 'hard'),
  ('Cloudflare', 'cloudflare', 'cloud', 'hard'),
  ('Kubernetes', 'kubernetes', 'cloud', 'hard'),
  ('Kubernetes', 'k8s', 'cloud', 'hard'),
  ('Docker', 'docker', 'cloud', 'hard'),
  ('Terraform', 'terraform', 'cloud', 'hard'),
  ('Ansible', 'ansible', 'cloud', 'hard'),
  ('Puppet', 'puppet', 'cloud', 'hard'),
  ('Chef', 'chef', 'cloud', 'hard'),
  ('Jenkins', 'jenkins', 'cloud', 'hard'),
  ('GitLab CI', 'gitlab ci', 'cloud', 'hard'),
  ('GitHub Actions', 'github actions', 'cloud', 'hard'),
  ('CircleCI', 'circleci', 'cloud', 'hard'),
  ('ArgoCD', 'argocd', 'cloud', 'hard'),
  ('Helm', 'helm', 'cloud', 'hard'),
  ('Prometheus', 'prometheus', 'cloud', 'hard'),
  ('Grafana', 'grafana', 'cloud', 'hard'),
  ('Datadog', 'datadog', 'cloud', 'hard'),
  ('New Relic', 'new relic', 'cloud', 'hard'),
  ('Splunk', 'splunk', 'cloud', 'hard'),
  ('Nginx', 'nginx', 'cloud', 'hard'),
  ('Apache', 'apache', 'cloud', 'hard'),
  ('Linux', 'linux', 'cloud', 'hard'),
  ('Windows Server', 'windows server', 'cloud', 'hard'),
  ('CI/CD', 'ci/cd', 'cloud', 'hard'),
  ('DevOps', 'devops', 'cloud', 'hard'),
  ('Site reliability engineering', 'site reliability engineering', 'cloud', 'hard'),
  ('Serverless', 'serverless', 'cloud', 'hard'),
  ('Lambda', 'lambda', 'cloud', 'hard'),
  ('EC2', 'ec2', 'cloud', 'hard'),
  ('S3', 's3', 'cloud', 'hard'),
  ('Kubernetes Operators', 'kubernetes operators', 'cloud', 'hard'),
  ('Power BI', 'power bi', 'analytics', 'hard'),
  ('Power BI', 'powerbi', 'analytics', 'hard'),
  ('Power BI', 'power-bi', 'analytics', 'hard'),
  ('Tableau', 'tableau', 'analytics', 'hard'),
  ('Looker', 'looker', 'analytics', 'hard'),
  ('Qlik', 'qlik', 'analytics', 'hard'),
  ('Excel', 'excel', 'analytics', 'hard'),
  ('Excel', 'microsoft excel', 'analytics', 'hard'),
  ('Excel', 'ms excel', 'analytics', 'hard'),
  ('Excel', 'advanced excel', 'analytics', 'hard'),
  ('Google Analytics', 'google analytics', 'analytics', 'hard'),
  ('Adobe Analytics', 'adobe analytics', 'analytics', 'hard'),
  ('SPSS', 'spss', 'analytics', 'hard'),
  ('SAS', 'sas', 'analytics', 'hard'),
  ('Stata', 'stata', 'analytics', 'hard'),
  ('Alteryx', 'alteryx', 'analytics', 'hard'),
  ('Domo', 'domo', 'analytics', 'hard'),
  ('Metabase', 'metabase', 'analytics', 'hard'),
  ('Superset', 'superset', 'analytics', 'hard'),
  ('Data visualisation', 'data visualisation', 'analytics', 'hard'),
  ('Data visualisation', 'data visualization', 'analytics', 'hard'),
  ('Statistical analysis', 'statistical analysis', 'analytics', 'hard'),
  ('A/B testing', 'a/b testing', 'analytics', 'hard'),
  ('Forecasting', 'forecasting', 'analytics', 'hard'),
  ('Regression analysis', 'regression analysis', 'analytics', 'hard'),
  ('Time series analysis', 'time series analysis', 'analytics', 'hard'),
  ('Machine learning', 'machine learning', 'ml', 'hard'),
  ('Machine learning', 'ml', 'ml', 'hard'),
  ('Deep learning', 'deep learning', 'ml', 'hard'),
  ('TensorFlow', 'tensorflow', 'ml', 'hard'),
  ('PyTorch', 'pytorch', 'ml', 'hard'),
  ('scikit-learn', 'scikit-learn', 'ml', 'hard'),
  ('scikit-learn', 'sklearn', 'ml', 'hard'),
  ('scikit-learn', 'scikit learn', 'ml', 'hard'),
  ('Keras', 'keras', 'ml', 'hard'),
  ('NumPy', 'numpy', 'ml', 'hard'),
  ('pandas', 'pandas', 'ml', 'hard'),
  ('Natural language processing', 'natural language processing', 'ml', 'hard'),
  ('Natural language processing', 'nlp', 'ml', 'hard'),
  ('Computer vision', 'computer vision', 'ml', 'hard'),
  ('Computer vision', 'cv (computer vision)', 'ml', 'hard'),
  ('MLOps', 'mlops', 'ml', 'hard'),
  ('XGBoost', 'xgboost', 'ml', 'hard'),
  ('Hugging Face', 'hugging face', 'ml', 'hard'),
  ('LangChain', 'langchain', 'ml', 'hard'),
  ('Prompt engineering', 'prompt engineering', 'ml', 'hard'),
  ('Recommender systems', 'recommender systems', 'ml', 'hard'),
  ('Reinforcement learning', 'reinforcement learning', 'ml', 'hard'),
  ('Figma', 'figma', 'design', 'hard'),
  ('Sketch', 'sketch', 'design', 'hard'),
  ('Adobe XD', 'adobe xd', 'design', 'hard'),
  ('Photoshop', 'photoshop', 'design', 'hard'),
  ('Illustrator', 'illustrator', 'design', 'hard'),
  ('InDesign', 'indesign', 'design', 'hard'),
  ('After Effects', 'after effects', 'design', 'hard'),
  ('Premiere Pro', 'premiere pro', 'design', 'hard'),
  ('Canva', 'canva', 'design', 'hard'),
  ('InVision', 'invision', 'design', 'hard'),
  ('Framer', 'framer', 'design', 'hard'),
  ('Blender', 'blender', 'design', 'hard'),
  ('AutoCAD', 'autocad', 'design', 'hard'),
  ('SolidWorks', 'solidworks', 'design', 'hard'),
  ('Revit', 'revit', 'design', 'hard'),
  ('SketchUp', 'sketchup', 'design', 'hard'),
  ('Wireframing', 'wireframing', 'design', 'hard'),
  ('Prototyping', 'prototyping', 'design', 'hard'),
  ('Design systems', 'design systems', 'design', 'hard'),
  ('Design systems', 'design system', 'design', 'hard'),
  ('Typography', 'typography', 'design', 'hard'),
  ('User research', 'user research', 'design', 'hard'),
  ('Usability testing', 'usability testing', 'design', 'hard'),
  ('Accessibility', 'accessibility', 'design', 'hard'),
  ('WCAG', 'wcag', 'design', 'hard'),
  ('Salesforce', 'salesforce', 'business', 'hard'),
  ('HubSpot', 'hubspot', 'business', 'hard'),
  ('Workday', 'workday', 'business', 'hard'),
  ('SAP', 'sap', 'business', 'hard'),
  ('Oracle ERP', 'oracle erp', 'business', 'hard'),
  ('NetSuite', 'netsuite', 'business', 'hard'),
  ('Dynamics 365', 'dynamics 365', 'business', 'hard'),
  ('ServiceNow', 'servicenow', 'business', 'hard'),
  ('Zendesk', 'zendesk', 'business', 'hard'),
  ('Jira', 'jira', 'business', 'hard'),
  ('Confluence', 'confluence', 'business', 'hard'),
  ('Asana', 'asana', 'business', 'hard'),
  ('Monday.com', 'monday.com', 'business', 'hard'),
  ('Trello', 'trello', 'business', 'hard'),
  ('Notion', 'notion', 'business', 'hard'),
  ('SharePoint', 'sharepoint', 'business', 'hard'),
  ('Microsoft Project', 'microsoft project', 'business', 'hard'),
  ('Smartsheet', 'smartsheet', 'business', 'hard'),
  ('Airtable', 'airtable', 'business', 'hard'),
  ('Slack', 'slack', 'business', 'hard'),
  ('Zoom', 'zoom', 'business', 'hard'),
  ('Miro', 'miro', 'business', 'hard'),
  ('Xero', 'xero', 'finance', 'hard'),
  ('QuickBooks', 'quickbooks', 'finance', 'hard'),
  ('MYOB', 'myob', 'finance', 'hard'),
  ('Sage', 'sage', 'finance', 'hard'),
  ('Financial modelling', 'financial modelling', 'finance', 'hard'),
  ('Financial modelling', 'financial modeling', 'finance', 'hard'),
  ('Budgeting', 'budgeting', 'finance', 'hard'),
  ('Management accounting', 'management accounting', 'finance', 'hard'),
  ('Management accounting', 'managerial accounting', 'finance', 'hard'),
  ('Financial reporting', 'financial reporting', 'finance', 'hard'),
  ('IFRS', 'ifrs', 'finance', 'hard'),
  ('GAAP', 'gaap', 'finance', 'hard'),
  ('Accounts payable', 'accounts payable', 'finance', 'hard'),
  ('Accounts receivable', 'accounts receivable', 'finance', 'hard'),
  ('Payroll', 'payroll', 'finance', 'hard'),
  ('Reconciliation', 'reconciliation', 'finance', 'hard'),
  ('Auditing', 'auditing', 'finance', 'hard'),
  ('Tax compliance', 'tax compliance', 'finance', 'hard'),
  ('Cost accounting', 'cost accounting', 'finance', 'hard'),
  ('Treasury', 'treasury', 'finance', 'hard'),
  ('Variance analysis', 'variance analysis', 'finance', 'hard'),
  ('P&L management', 'p&l management', 'finance', 'hard'),
  ('P&L management', 'p&l', 'finance', 'hard'),
  ('P&L management', 'profit and loss', 'finance', 'hard'),
  ('Cash flow management', 'cash flow management', 'finance', 'hard'),
  ('SEO', 'seo', 'marketing', 'hard'),
  ('SEO', 'search engine optimisation', 'marketing', 'hard'),
  ('SEO', 'search engine optimization', 'marketing', 'hard'),
  ('SEM', 'sem', 'marketing', 'hard'),
  ('Google Ads', 'google ads', 'marketing', 'hard'),
  ('Meta Ads', 'meta ads', 'marketing', 'hard'),
  ('LinkedIn Ads', 'linkedin ads', 'marketing', 'hard'),
  ('Email marketing', 'email marketing', 'marketing', 'hard'),
  ('Mailchimp', 'mailchimp', 'marketing', 'hard'),
  ('Klaviyo', 'klaviyo', 'marketing', 'hard'),
  ('Content marketing', 'content marketing', 'marketing', 'hard'),
  ('Copywriting', 'copywriting', 'marketing', 'hard'),
  ('Social media marketing', 'social media marketing', 'marketing', 'hard'),
  ('Marketing automation', 'marketing automation', 'marketing', 'hard'),
  ('Marketo', 'marketo', 'marketing', 'hard'),
  ('Pardot', 'pardot', 'marketing', 'hard'),
  ('Conversion rate optimisation', 'conversion rate optimisation', 'marketing', 'hard'),
  ('Conversion rate optimisation', 'cro', 'marketing', 'hard'),
  ('Brand strategy', 'brand strategy', 'marketing', 'hard'),
  ('Market research', 'market research', 'marketing', 'hard'),
  ('Campaign management', 'campaign management', 'marketing', 'hard'),
  ('Google Tag Manager', 'google tag manager', 'marketing', 'hard'),
  ('Affiliate marketing', 'affiliate marketing', 'marketing', 'hard'),
  ('Lean', 'lean', 'ops', 'hard'),
  ('Six Sigma', 'six sigma', 'ops', 'hard'),
  ('Six Sigma', '6 sigma', 'ops', 'hard'),
  ('Six Sigma', 'lean six sigma', 'ops', 'hard'),
  ('Kaizen', 'kaizen', 'ops', 'hard'),
  ('Process design', 'process design', 'ops', 'hard'),
  ('Process improvement', 'process improvement', 'ops', 'hard'),
  ('Process improvement', 'business process improvement', 'ops', 'hard'),
  ('Supply chain management', 'supply chain management', 'ops', 'hard'),
  ('Supply chain management', 'supply chain', 'ops', 'hard'),
  ('Logistics', 'logistics', 'ops', 'hard'),
  ('Procurement', 'procurement', 'ops', 'hard'),
  ('Inventory management', 'inventory management', 'ops', 'hard'),
  ('Demand planning', 'demand planning', 'ops', 'hard'),
  ('Warehouse management', 'warehouse management', 'ops', 'hard'),
  ('Quality assurance', 'quality assurance', 'ops', 'hard'),
  ('Quality assurance', 'qa', 'ops', 'hard'),
  ('Quality control', 'quality control', 'ops', 'hard'),
  ('ISO 9001', 'iso 9001', 'ops', 'hard'),
  ('Health and safety', 'health and safety', 'ops', 'hard'),
  ('Contract negotiation', 'contract negotiation', 'ops', 'hard'),
  ('Contract negotiation', 'negotiation', 'ops', 'hard'),
  ('Vendor management', 'vendor management', 'ops', 'hard'),
  ('Capacity planning', 'capacity planning', 'ops', 'hard'),
  ('Route optimisation', 'route optimisation', 'ops', 'hard'),
  ('Continuous improvement', 'continuous improvement', 'ops', 'hard'),
  ('Continuous improvement', 'ci (continuous improvement)', 'ops', 'hard'),
  ('Root cause analysis', 'root cause analysis', 'ops', 'hard'),
  ('Root cause analysis', 'rca', 'ops', 'hard'),
  ('Standard operating procedures', 'standard operating procedures', 'ops', 'hard'),
  ('Agile', 'agile', 'pm', 'hard'),
  ('Scrum', 'scrum', 'pm', 'hard'),
  ('Kanban', 'kanban', 'pm', 'hard'),
  ('SAFe', 'safe', 'pm', 'hard'),
  ('PRINCE2', 'prince2', 'pm', 'hard'),
  ('PMP', 'pmp', 'pm', 'hard'),
  ('Waterfall', 'waterfall', 'pm', 'hard'),
  ('Product management', 'product management', 'pm', 'hard'),
  ('Roadmapping', 'roadmapping', 'pm', 'hard'),
  ('Backlog management', 'backlog management', 'pm', 'hard'),
  ('Sprint planning', 'sprint planning', 'pm', 'hard'),
  ('Stakeholder management', 'stakeholder management', 'pm', 'hard'),
  ('Stakeholder management', 'stakeholder engagement', 'pm', 'hard'),
  ('Risk management', 'risk management', 'pm', 'hard'),
  ('Change management', 'change management', 'pm', 'hard'),
  ('Programme management', 'programme management', 'pm', 'hard'),
  ('Business analysis', 'business analysis', 'pm', 'hard'),
  ('Requirements gathering', 'requirements gathering', 'pm', 'hard'),
  ('User stories', 'user stories', 'pm', 'hard'),
  ('Product discovery', 'product discovery', 'pm', 'hard'),
  ('OKRs', 'okrs', 'pm', 'hard'),
  ('Cybersecurity', 'cybersecurity', 'security', 'hard'),
  ('Penetration testing', 'penetration testing', 'security', 'hard'),
  ('Incident response', 'incident response', 'security', 'hard'),
  ('SIEM', 'siem', 'security', 'hard'),
  ('Vulnerability management', 'vulnerability management', 'security', 'hard'),
  ('Identity and access management', 'identity and access management', 'security', 'hard'),
  ('Identity and access management', 'iam', 'security', 'hard'),
  ('Zero trust', 'zero trust', 'security', 'hard'),
  ('ISO 27001', 'iso 27001', 'security', 'hard'),
  ('SOC 2', 'soc 2', 'security', 'hard'),
  ('GDPR', 'gdpr', 'security', 'hard'),
  ('Risk assessment', 'risk assessment', 'security', 'hard'),
  ('Encryption', 'encryption', 'security', 'hard'),
  ('Firewall management', 'firewall management', 'security', 'hard'),
  ('Threat modelling', 'threat modelling', 'security', 'hard'),
  ('Security auditing', 'security auditing', 'security', 'hard'),
  ('Patient care', 'patient care', 'health', 'hard'),
  ('Clinical assessment', 'clinical assessment', 'health', 'hard'),
  ('Medication administration', 'medication administration', 'health', 'hard'),
  ('Infection control', 'infection control', 'health', 'hard'),
  ('Triage', 'triage', 'health', 'hard'),
  ('Care planning', 'care planning', 'health', 'hard'),
  ('Electronic health records', 'electronic health records', 'health', 'hard'),
  ('Electronic health records', 'ehr', 'health', 'hard'),
  ('Electronic health records', 'emr', 'health', 'hard'),
  ('Phlebotomy', 'phlebotomy', 'health', 'hard'),
  ('CPR', 'cpr', 'health', 'hard'),
  ('First aid', 'first aid', 'health', 'hard'),
  ('Mental health support', 'mental health support', 'health', 'hard'),
  ('Rehabilitation', 'rehabilitation', 'health', 'hard'),
  ('Safeguarding', 'safeguarding', 'health', 'hard'),
  ('Curriculum design', 'curriculum design', 'education', 'hard'),
  ('Lesson planning', 'lesson planning', 'education', 'hard'),
  ('Classroom management', 'classroom management', 'education', 'hard'),
  ('Assessment design', 'assessment design', 'education', 'hard'),
  ('Differentiated instruction', 'differentiated instruction', 'education', 'hard'),
  ('Special educational needs', 'special educational needs', 'education', 'hard'),
  ('Tutoring', 'tutoring', 'education', 'hard'),
  ('Learning management systems', 'learning management systems', 'education', 'hard'),
  ('E-learning', 'e-learning', 'education', 'hard'),
  ('Instructional design', 'instructional design', 'education', 'hard'),
  ('Contract law', 'contract law', 'legal', 'hard'),
  ('Contract drafting', 'contract drafting', 'legal', 'hard'),
  ('Legal research', 'legal research', 'legal', 'hard'),
  ('Due diligence', 'due diligence', 'legal', 'hard'),
  ('Compliance', 'compliance', 'legal', 'hard'),
  ('Litigation support', 'litigation support', 'legal', 'hard'),
  ('Intellectual property', 'intellectual property', 'legal', 'hard'),
  ('Employment law', 'employment law', 'legal', 'hard'),
  ('Regulatory reporting', 'regulatory reporting', 'legal', 'hard'),
  ('Corporate governance', 'corporate governance', 'legal', 'hard'),
  ('Communication', 'communication', 'soft', 'soft'),
  ('Teamwork', 'teamwork', 'soft', 'soft'),
  ('Leadership', 'leadership', 'soft', 'soft'),
  ('Problem solving', 'problem solving', 'soft', 'soft'),
  ('Time management', 'time management', 'soft', 'soft'),
  ('Adaptability', 'adaptability', 'soft', 'soft'),
  ('Creativity', 'creativity', 'soft', 'soft'),
  ('Attention to detail', 'attention to detail', 'soft', 'soft'),
  ('Collaboration', 'collaboration', 'soft', 'soft'),
  ('Critical thinking', 'critical thinking', 'soft', 'soft'),
  ('Decision making', 'decision making', 'soft', 'soft'),
  ('Emotional intelligence', 'emotional intelligence', 'soft', 'soft'),
  ('Conflict resolution', 'conflict resolution', 'soft', 'soft'),
  ('Presentation skills', 'presentation skills', 'soft', 'soft'),
  ('Mentoring', 'mentoring', 'soft', 'soft'),
  ('Coaching', 'coaching', 'soft', 'soft'),
  ('Customer service', 'customer service', 'soft', 'soft'),
  ('Interpersonal skills', 'interpersonal skills', 'soft', 'soft'),
  ('Organisation', 'organisation', 'soft', 'soft'),
  ('Resilience', 'resilience', 'soft', 'soft'),
  ('Negotiation skills', 'negotiation skills', 'soft', 'soft'),
  ('Active listening', 'active listening', 'soft', 'soft'),
  ('Cross-functional working', 'cross-functional working', 'soft', 'soft'),
  ('Public speaking', 'public speaking', 'soft', 'soft'),
  ('Written communication', 'written communication', 'soft', 'soft');
