// Three spelling lexicons that all feed D09.
//
// The check is about CONSISTENCY, not correctness: British and American
// spelling are both right, and a CV that uses both in the same document reads
// as assembled from pieces. So variants are stored as pairs and only reported
// when both halves appear.

/** UK -> US pairs. Reported only when a document contains both spellings. */
export const SPELLING_VARIANTS = [
  ['analyse', 'analyze'], ['analysed', 'analyzed'], ['analysing', 'analyzing'],
  ['apologise', 'apologize'], ['authorise', 'authorize'], ['authorised', 'authorized'],
  ['behaviour', 'behavior'], ['calibre', 'caliber'], ['cancelled', 'canceled'],
  ['catalogue', 'catalog'], ['categorise', 'categorize'], ['centre', 'center'],
  ['centralise', 'centralize'], ['cheque', 'check'], ['colour', 'color'],
  ['colours', 'colors'], ['counselling', 'counseling'], ['criticise', 'criticize'],
  ['customise', 'customize'], ['customised', 'customized'], ['defence', 'defense'],
  ['dependant', 'dependent'], ['dialogue', 'dialog'], ['digitise', 'digitize'],
  ['emphasise', 'emphasize'], ['enrol', 'enroll'], ['enrolment', 'enrollment'],
  ['favour', 'favor'], ['favourite', 'favorite'], ['fibre', 'fiber'],
  ['formalise', 'formalize'], ['fulfil', 'fulfill'], ['fulfilment', 'fulfillment'],
  ['grey', 'gray'], ['harbour', 'harbor'], ['honour', 'honor'],
  ['humour', 'humor'], ['initialise', 'initialize'], ['judgement', 'judgment'],
  ['labelled', 'labeled'], ['labour', 'labor'], ['licence', 'license'],
  ['litre', 'liter'], ['maximise', 'maximize'], ['metre', 'meter'],
  ['minimise', 'minimize'], ['modelled', 'modeled'], ['modernise', 'modernize'],
  ['neighbour', 'neighbor'], ['normalise', 'normalize'], ['offence', 'offense'],
  ['optimise', 'optimize'], ['optimised', 'optimized'], ['organisation', 'organization'],
  ['organise', 'organize'], ['organised', 'organized'], ['practise', 'practice'],
  ['prioritise', 'prioritize'], ['prioritised', 'prioritized'], ['programme', 'program'],
  ['rationalise', 'rationalize'], ['realise', 'realize'], ['realised', 'realized'],
  ['recognise', 'recognize'], ['recognised', 'recognized'], ['specialise', 'specialize'],
  ['specialised', 'specialized'], ['standardise', 'standardize'], ['summarise', 'summarize'],
  ['synthesise', 'synthesize'], ['theatre', 'theater'], ['travelled', 'traveled'],
  ['utilise', 'utilize'], ['visualise', 'visualize'],
];

/** Outright misspellings, with the correction shown to the reader. */
export const TYPOS = new Map(Object.entries({
  acheived: 'achieved', acheive: 'achieve', accomodate: 'accommodate',
  accomodated: 'accommodated', acheivement: 'achievement', adress: 'address',
  advertisment: 'advertisement', agressive: 'aggressive', alot: 'a lot',
  anaylsis: 'analysis', apparant: 'apparent', arguement: 'argument',
  assesment: 'assessment', assistent: 'assistant', begining: 'beginning',
  beleive: 'believe', benifit: 'benefit', buisness: 'business',
  bussiness: 'business', calender: 'calendar', catagory: 'category',
  cheif: 'chief', collegue: 'colleague', comitted: 'committed',
  commited: 'committed', competant: 'competent', concious: 'conscious',
  consistant: 'consistent', continous: 'continuous', cordinator: 'coordinator',
  curriculam: 'curriculum', decison: 'decision', definately: 'definitely',
  dependancy: 'dependency', desicion: 'decision', developement: 'development',
  diffrent: 'different', dissapointed: 'disappointed', efficency: 'efficiency',
  embarass: 'embarrass', enviroment: 'environment', excelent: 'excellent',
  existance: 'existence', experiance: 'experience', experianced: 'experienced',
  familar: 'familiar', finacial: 'financial', foriegn: 'foreign',
  fourty: 'forty', freind: 'friend', fullfil: 'fulfil',
  garantee: 'guarantee', goverment: 'government', gratefull: 'grateful',
  hierachy: 'hierarchy', imediately: 'immediately', independant: 'independent',
  intergration: 'integration', interviewd: 'interviewed', knowlege: 'knowledge',
  liason: 'liaison', maintainance: 'maintenance', managment: 'management',
  managerial: 'managerial', mangement: 'management', neccessary: 'necessary',
  negotiaton: 'negotiation', noticable: 'noticeable', occassion: 'occasion',
  occured: 'occurred', occuring: 'occurring', oppurtunity: 'opportunity',
  oportunity: 'opportunity', paticularly: 'particularly', percieve: 'perceive',
  performace: 'performance', perseverence: 'perseverance', personel: 'personnel',
  posession: 'possession', preformed: 'performed', priviledge: 'privilege',
  probaly: 'probably', proffesional: 'professional', proffessional: 'professional',
  publically: 'publicly', recieve: 'receive', recieved: 'received',
  recomend: 'recommend', recomended: 'recommended', refered: 'referred',
  relevent: 'relevant', reponsible: 'responsible', responsable: 'responsible',
  responsibile: 'responsible', restaraunt: 'restaurant', reccomend: 'recommend',
  reponsibilities: 'responsibilities', seperate: 'separate', seperated: 'separated',
  sincerly: 'sincerely', sucessful: 'successful', succesful: 'successful',
  successfull: 'successful', supervisior: 'supervisor', suprise: 'surprise',
  targetted: 'targeted', teh: 'the', temperment: 'temperament',
  thier: 'their', threshhold: 'threshold', tommorow: 'tomorrow',
  truely: 'truly', untill: 'until', vaccum: 'vacuum',
  wich: 'which', writting: 'writing', yeild: 'yield',
}));

/** Product names whose casing is part of the name (D09). */
export const BRAND_CASING = new Map(Object.entries({
  javascript: 'JavaScript', typescript: 'TypeScript', github: 'GitHub',
  gitlab: 'GitLab', linkedin: 'LinkedIn', postgresql: 'PostgreSQL',
  postgres: 'PostgreSQL', mysql: 'MySQL', mongodb: 'MongoDB',
  nodejs: 'Node.js', 'node js': 'Node.js', reactjs: 'React',
  vuejs: 'Vue.js', angularjs: 'AngularJS', nextjs: 'Next.js',
  graphql: 'GraphQL', restful: 'RESTful', json: 'JSON',
  html: 'HTML', css: 'CSS', sql: 'SQL', nosql: 'NoSQL',
  php: 'PHP', dotnet: '.NET', csharp: 'C#', 'c sharp': 'C#',
  kubernetes: 'Kubernetes', docker: 'Docker', jenkins: 'Jenkins',
  terraform: 'Terraform', ansible: 'Ansible', kafka: 'Kafka',
  elasticsearch: 'Elasticsearch', redis: 'Redis', rabbitmq: 'RabbitMQ',
  aws: 'AWS', gcp: 'GCP', azure: 'Azure', devops: 'DevOps',
  cicd: 'CI/CD', macos: 'macOS', ios: 'iOS', android: 'Android',
  windows: 'Windows', linux: 'Linux', ubuntu: 'Ubuntu',
  powerbi: 'Power BI', 'power bi': 'Power BI', tableau: 'Tableau',
  salesforce: 'Salesforce', hubspot: 'HubSpot', workday: 'Workday',
  sharepoint: 'SharePoint', quickbooks: 'QuickBooks', xero: 'Xero',
  sap: 'SAP', oracle: 'Oracle', jira: 'Jira', confluence: 'Confluence',
  photoshop: 'Photoshop', illustrator: 'Illustrator', indesign: 'InDesign',
  figma: 'Figma', sketch: 'Sketch', wordpress: 'WordPress',
  shopify: 'Shopify', magento: 'Magento', pytorch: 'PyTorch',
  tensorflow: 'TensorFlow', numpy: 'NumPy', pandas: 'pandas',
  scikit: 'scikit-learn', matlab: 'MATLAB', excel: 'Excel',
  powerpoint: 'PowerPoint', outlook: 'Outlook', slack: 'Slack',
  zoom: 'Zoom', trello: 'Trello', asana: 'Asana', notion: 'Notion',
  openai: 'OpenAI', anthropic: 'Anthropic', kotlin: 'Kotlin',
  swift: 'Swift', golang: 'Go', rustlang: 'Rust', ruby: 'Ruby',
  django: 'Django', flask: 'Flask', spring: 'Spring', laravel: 'Laravel',
  bootstrap: 'Bootstrap', tailwind: 'Tailwind CSS', webpack: 'webpack',
  npm: 'npm', yarn: 'Yarn', eslint: 'ESLint', jest: 'Jest',
  cypress: 'Cypress', selenium: 'Selenium', postman: 'Postman',
  scrum: 'Scrum', kanban: 'Kanban', prince2: 'PRINCE2', pmp: 'PMP',
  itil: 'ITIL', iso: 'ISO', gdpr: 'GDPR', saas: 'SaaS', api: 'API',
}));

/** Acronyms common enough that D11 does not ask for an expansion. */
export const KNOWN_ACRONYMS = new Set([
  'API', 'APIs', 'AWS', 'B2B', 'B2C', 'BI', 'CEO', 'CFO', 'CI', 'CD',
  'CIO', 'CMS', 'COO', 'CPA', 'CRM', 'CSS', 'CTO', 'CV', 'DNS', 'EU',
  'ERP', 'ESG', 'ETL', 'EU', 'FTE', 'GDP', 'GDPR', 'GPA', 'HR', 'HTML',
  'HTTP', 'HTTPS', 'IT', 'ISO', 'ITIL', 'JSON', 'KPI', 'KPIs', 'MBA',
  'ML', 'NDA', 'NGO', 'OKR', 'OKRs', 'PDF', 'PHP', 'PMO', 'PMP', 'QA',
  'R&D', 'REST', 'ROI', 'SaaS', 'SDK', 'SEO', 'SLA', 'SME', 'SQL',
  'SSL', 'TDD', 'UI', 'UK', 'URL', 'US', 'USA', 'USD', 'UX', 'VAT',
  'VP', 'XML', 'YoY', 'AI', 'AR', 'VR', 'IOT', 'IoT', 'P&L', 'GBP',
  'EUR', 'NZD', 'AUD', 'CAD', 'PhD', 'BSc', 'MSc', 'BA', 'MA', 'BEng',
]);

/** Words carrying no meaning for keyword matching. */
export const STOPWORDS = new Set([
  'a', 'about', 'above', 'across', 'after', 'again', 'against', 'all', 'also',
  'am', 'among', 'an', 'and', 'any', 'are', 'as', 'at', 'be', 'because',
  'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can',
  'could', 'did', 'do', 'does', 'doing', 'down', 'during', 'each', 'either',
  'few', 'for', 'from', 'further', 'had', 'has', 'have', 'having', 'he',
  'her', 'here', 'hers', 'him', 'his', 'how', 'i', 'if', 'in', 'into', 'is',
  'it', 'its', 'itself', 'just', 'me', 'more', 'most', 'my', 'myself', 'no',
  'nor', 'not', 'now', 'of', 'off', 'on', 'once', 'only', 'or', 'other',
  'our', 'ours', 'out', 'over', 'own', 'per', 'same', 'she', 'should', 'so',
  'some', 'such', 'than', 'that', 'the', 'their', 'theirs', 'them', 'then',
  'there', 'these', 'they', 'this', 'those', 'through', 'to', 'too', 'under',
  'until', 'up', 'very', 'was', 'we', 'were', 'what', 'when', 'where',
  'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'within', 'would',
  'you', 'your', 'yours', 'etc', 'via', 'using', 'used', 'use', 'including',
  'include', 'well', 'able', 'across', 'various', 'strong', 'excellent',
  'good', 'great', 'new', 'role', 'work', 'working', 'years', 'year',
]);
